# Generated by Django 2.2.6 on 2019-10-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='blood_pressure_diastolic',
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
