# Generated by Django 2.2.6 on 2019-10-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_auto_20191027_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(choices=[('adderall', 'Adderall'), ('lisinopril', 'Lisinopril'), ('vyvanse', 'Vyvanse')], max_length=256),
        ),
    ]
