# Generated by Django 2.2.6 on 2019-10-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpressures', '0002_auto_20191027_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
