# Generated by Django 2.2.6 on 2019-10-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpressures', '0003_auto_20191027_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
